-- Convert state abbreviations to full names
-- This migration updates existing tournament records from abbreviations to full state names

UPDATE tournaments SET state = 'Alabama' WHERE state = 'AL';
UPDATE tournaments SET state = 'Alaska' WHERE state = 'AK';
UPDATE tournaments SET state = 'Arizona' WHERE state = 'AZ';
UPDATE tournaments SET state = 'Arkansas' WHERE state = 'AR';
UPDATE tournaments SET state = 'California' WHERE state = 'CA';
UPDATE tournaments SET state = 'Colorado' WHERE state = 'CO';
UPDATE tournaments SET state = 'Connecticut' WHERE state = 'CT';
UPDATE tournaments SET state = 'Delaware' WHERE state = 'DE';
UPDATE tournaments SET state = 'Florida' WHERE state = 'FL';
UPDATE tournaments SET state = 'Georgia' WHERE state = 'GA';
UPDATE tournaments SET state = 'Hawaii' WHERE state = 'HI';
UPDATE tournaments SET state = 'Idaho' WHERE state = 'ID';
UPDATE tournaments SET state = 'Illinois' WHERE state = 'IL';
UPDATE tournaments SET state = 'Indiana' WHERE state = 'IN';
UPDATE tournaments SET state = 'Iowa' WHERE state = 'IA';
UPDATE tournaments SET state = 'Kansas' WHERE state = 'KS';
UPDATE tournaments SET state = 'Kentucky' WHERE state = 'KY';
UPDATE tournaments SET state = 'Louisiana' WHERE state = 'LA';
UPDATE tournaments SET state = 'Maine' WHERE state = 'ME';
UPDATE tournaments SET state = 'Maryland' WHERE state = 'MD';
UPDATE tournaments SET state = 'Massachusetts' WHERE state = 'MA';
UPDATE tournaments SET state = 'Michigan' WHERE state = 'MI';
UPDATE tournaments SET state = 'Minnesota' WHERE state = 'MN';
UPDATE tournaments SET state = 'Mississippi' WHERE state = 'MS';
UPDATE tournaments SET state = 'Missouri' WHERE state = 'MO';
UPDATE tournaments SET state = 'Montana' WHERE state = 'MT';
UPDATE tournaments SET state = 'Nebraska' WHERE state = 'NE';
UPDATE tournaments SET state = 'Nevada' WHERE state = 'NV';
UPDATE tournaments SET state = 'New Hampshire' WHERE state = 'NH';
UPDATE tournaments SET state = 'New Jersey' WHERE state = 'NJ';
UPDATE tournaments SET state = 'New Mexico' WHERE state = 'NM';
UPDATE tournaments SET state = 'New York' WHERE state = 'NY';
UPDATE tournaments SET state = 'North Carolina' WHERE state = 'NC';
UPDATE tournaments SET state = 'North Dakota' WHERE state = 'ND';
UPDATE tournaments SET state = 'Ohio' WHERE state = 'OH';
UPDATE tournaments SET state = 'Oklahoma' WHERE state = 'OK';
UPDATE tournaments SET state = 'Oregon' WHERE state = 'OR';
UPDATE tournaments SET state = 'Pennsylvania' WHERE state = 'PA';
UPDATE tournaments SET state = 'Rhode Island' WHERE state = 'RI';
UPDATE tournaments SET state = 'South Carolina' WHERE state = 'SC';
UPDATE tournaments SET state = 'South Dakota' WHERE state = 'SD';
UPDATE tournaments SET state = 'Tennessee' WHERE state = 'TN';
UPDATE tournaments SET state = 'Texas' WHERE state = 'TX';
UPDATE tournaments SET state = 'Utah' WHERE state = 'UT';
UPDATE tournaments SET state = 'Vermont' WHERE state = 'VT';
UPDATE tournaments SET state = 'Virginia' WHERE state = 'VA';
UPDATE tournaments SET state = 'Washington' WHERE state = 'WA';
UPDATE tournaments SET state = 'West Virginia' WHERE state = 'WV';
UPDATE tournaments SET state = 'Wisconsin' WHERE state = 'WI';
UPDATE tournaments SET state = 'Wyoming' WHERE state = 'WY';
